### ISSUE TITLE
feature request: scroll height/percentage for volume button scrolling

### ISSUE THREAD

**Issue by Spleeeno** [yanus171/Flym#101]
hey there,

if I set the volume buttons to scroll up/down, it seems to "overscroll" compared to when I use the xupdown xposed module to achieve the same thing.
so with your setting I scroll down and have no idea where I was in the text cause it scrolls a bit too far.
with xupdown it gives me 2-3 lines from the old page, which is a perfect starting point for me.
would it be possible to introduce a scroll percentage or some similar setting?

**Comment by yanus171** [comment]
Yes, I can do it. Propose a list of setting percentage values

**Comment by Spleeeno** [comment]
maybe just make it a checkbox that says something like "only scroll 90% or keep 3 lines from the previous screen on top"?

**Comment by yanus171** [comment]
I have added the corresponding setting at the bottom of the Article text category. Try https://github.com/yanus171/Flym/releases/tag/v0.7.52

**Comment by ThomasLeigh** [comment]
I'm not sure but it looks a kind of a better (?) way during scrolling (than before)... Is it true? Does it scroll differently now (even if this feature is off)?

**Comment by ThomasLeigh** [comment]
I mean the animation of scrolled text seems to look better/differently.

**Comment by yanus171** [comment]
Yes, a bit different. Scroll via animation mechanism. May be a bit faster. 
But why is better?

**Comment by ThomasLeigh** [comment]
It's a subjective sensation due to the animation being a little bit faster, I suppose.

**Comment by Spleeeno** [comment]
it's actually pretty neat: since the animation scale you can set in the android developer settings are now applied, the scrolling has actually become instantaneous for me. so this makes using the e-ink side of my phone a total treat - much appreciated.
