### ISSUE TITLE
Suggestion to the Translation Procedure

### ISSUE THREAD

**Issue by sr093906** [yanus171/Flym#114]
I suggest moving the translation work to a professional platform, such as Crowdin or Weblate, for long-term benefit (coordination,maintenance,change detection...).

**Comment by ThomasLeigh** [comment]
Is any of theses available for free?

**Comment by yanus171** [comment]
What are the beneficial differences of that platforms from github?

**Comment by sr093906** [comment]
@ThomasLeigh Webpage is free in charge if self hosted version is adopted. Not sure if it is developer friendly however. I heard about the platform since another FOSS app Kiss Launcher uses it.

**Comment by sr093906** [comment]
@yanus171 Generally, no big difference for developers as long as translations are available. They are more friendly to translators who did not own much technical knowledge,  like how to make a pull request.They just need to translate strings and will be notified via email to translate  if words/phrases are added or modified.

**Comment by ThomasLeigh** [comment]
So I need to download some CMS and install it on some web hosting?

**Comment by sr093906** [comment]
@ThomasLeigh Yes, that is what self hosted means. I am willing to offer some financial support each month such as USD5 if you needed since I love the app.

**Comment by ThomasLeigh** [comment]
@sr093906, thank You. I suppose there should be plenty of free hosting offers out there to fit this purpose. Although the benefits You've described I find appealing, I completely can't tell when I would be able to manage all this stuff. Nevertheless thank You for the idea and, btw, glad that You love the app! :)

**Comment by sr093906** [comment]
@ThomasLeigh No problem. Thanks for the reply.

**Comment by ThomasLeigh** [comment]
@sr093906 , I'd like to take a closer look on _Weblate_ (_Crowdin_ seems not to be free), but I'm not so technical to handle the installation procedure. I could set up some free hosting, but I have no idea how to install _Weblate_ on it. It seems not to be so simple as some _CMS_ installation, which I find pretty comprehensive.

**Comment by SIRSteiner** [comment]
Installation of Weblate needs access to run installation scripts at your webspace.

**Comment by ThomasLeigh** [comment]
Is it doable for Me as a non-techy user who can install a simple CMS? This was simply about putting CMS files on the FTP, opening installation setup through a web-browser, setting up a MySQL database and that's all.

**Comment by SIRSteiner** [comment]
I think no because you need more access to your web server than uploading and running a php installation setup.
