### ISSUE TITLE
New setting "Custom show read"

### ISSUE THREAD

**Issue by bcm314** [yanus171/Flym#136]
Maybe on some feed you prefere "show read", while on others you don't.
So how about a new setting "Custom show read"?
If enabled, for each feed this setting (the checkbox at top) is saved separately.

**Comment by yanus171** [comment]
Give me an example of such feeds

**Comment by bcm314** [comment]
Maybe it's misuse of a NEWS reader, but why not, if it works well.  ;-)

News should be read one time and than there is no more need of it (don't show it any longer).

But feeds showing "special offers" (for buying) I would like to see also read one.
Of course, if there is a special offer I'm waiting so long, I can put in on starred list, so I won't forget it.
(And maybe others I'm absolutely not interessted, I can delete.)
But the other would be nice to see.

Here is one example I use: https://boardgamegeek.com/rss/geeklist/72020

**Comment by yanus171** [comment]
So favorities are designed for that. Why they are not enough? And you can also mark article as unread

**Comment by bcm314** [comment]
It's realy not a big deal. I can only say, I switch often between 'show' and 'hide'.  ;-)
