### ISSUE TITLE
Problems while sorting feeds

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Flym#18]
To sort feeds you have to tap nearly the right margin. If you touch on the sort icon you cannot sort.

**Comment by yanus171** [comment]
Send me a screenshot. I do not understand where is a sort

**Comment by SIRSteiner** [comment]
![screenshot_20181222-212225_1545510387782](https://user-images.githubusercontent.com/3488638/50378769-0ef02600-063a-11e9-90fb-1cd03f441eee.png)
The red marked icon I mean. But I have to tap at the green field to move up and down.

**Comment by yanus171** [comment]
Ihas no such problem on my device. May be you should calibrate your screen.
С уважением, Алексей

SIRSteiner <notifications@github.com> 23 декабря 2018 г. 12:38:16 ДП написал:

**Comment by SIRSteiner** [comment]
No, this also happens in landscape and another smartphone here

**Comment by SIRSteiner** [comment]
With the latest commit this issue should be solved.

Cause: The tap width was defined by `getWidth() - 80` which is not related to any resolution and display size.

I tested this fix on my BQ M5, a 7" tablet and a 10" tablet.
If you can confirm it please let us close this issue.

Regards
Ronny
