### ISSUE TITLE
Error after clean install.

### ISSUE THREAD

**Issue by tico-tico** [yanus171/Flym#3]
I'm getting this phantom buggy subscription after clean install.
1. Clean install
2. Add any rss-feed

![_20180322_231356](https://user-images.githubusercontent.com/10702026/37796092-65f88ff0-2e27-11e8-92ea-d57170c10d37.JPG)

It can be deleted but it's not a very good first-run experience.

It's 0.6.15 from GP.

**Comment by yanus171** [comment]
В этой ленте хранятся статьи, загруженные с помощью пункта Читать меню 
поделиться других приложений
С уважением, Алексей

tico-tico <notifications@github.com> 22 марта 2018 г. 23:21:42 написал:

**Comment by tico-tico** [comment]
В том-то и дело, что я ещё ничего не загружал, а ошибка "лента не может быть добавлена" уже есть.

**Comment by Dreamer-4pda** [comment]
У меня эти пункты появляются регулярно и если их не удалять, то разростаются до бесконечности.
Сейчас их 2, но я теперь регулярно их чищу.

**Comment by yanus171** [comment]
Эта ошибка исправилась?

**Comment by Dreamer-4pda** [comment]
Да, новые пункты не появляются
