### ISSUE TITLE
A larger area for the swipe from the top to star/unstar feature.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Flym#43]
May I ask for a twice a higher area sensitive to this gesture? It would be of great help because now it isn't so easy to target it, especially quickly - and I often miss the area and trigger just a shadow indicating that it can't be scrolled further - instead of the actual function.

**Comment by yanus171** [comment]
Check please the current are in settings - tap zones. Does the issue really 
concerns with size of the area?
С уважением, Алексей

Thomas Leigh <notifications@github.com> 6 января 2019 г. 1:18:58 написал:

**Comment by ThomasLeigh** [comment]
Yes. Besides there is no information on this feature in tap zones description.

**Comment by yanus171** [comment]
This is a lack of translation. By the way you can track the github commit 
history to look for changes in strings.xml
С уважением, Алексей

Thomas Leigh <notifications@github.com> 6 января 2019 г. 7:37:47 написал:

**Comment by ThomasLeigh** [comment]
Oh, I see.

The initial idea of this feature was to be able to just swipe down on the beginning of the article (the whole of the screen height) in order to quickly and easily star it. Something similar to unstar when reaching the end - detecting the swipe down gesture which can't scroll the article anymore in a particular direction.

If it is too much hassle technically speaking -  it would be helpful to have twice a higher area for the current swipe down.

**Comment by yanus171** [comment]
Can you define the area size in mm?

**Comment by ThomasLeigh** [comment]
Would it be possible to define the height in %? Because in mm it won't be the same experience on various devices, especially with different screen ratios.

I've calculated the % which could be definitely convenient in use, especially with "lazy finger" ;) - and it is around **35% of the height of the screen**.

**Comment by ThomasLeigh** [comment]
Oh, I see: it works on a basis of the fixed, invisible tap-area, always present on the screen. Could You do it without tap area but by detecting a swipe down gesture which can't scroll the article further down (because there is nothing to scroll above the header?

I ask for this because it would be the best solution in which You could swipe down wherever on the screen -> the most convenient, simplest and easiest way to use.

If, however, is not possible  or You don't like to do it this way - I've checked My original idea and it is about 23% of the screen height.

**Comment by yanus171** [comment]
I see no sense in limiting this features by overscroll only. On the contrary, I often make a decision to star the article only after reading few pages, so I don't want to return to beginning and back again.

I propose to make a preference of page height percent star swipe area

**Comment by ThomasLeigh** [comment]
_"I propose to make a preference of page height percent star swipe area"_

Do You mean to set any height in app's settings?

**Comment by yanus171** [comment]
Yes

**Comment by ThomasLeigh** [comment]
It would be great :)

**Comment by yanus171** [comment]
And what about other tap zones? Is their current size not enough too?

**Comment by ThomasLeigh** [comment]
Thank You for asking, generally it is all right. Corner zones could be twice a bigger - but this is not so important/of an obstacle as the top one.

**Comment by yanus171** [comment]
One setting for top zone, one for bottom zone, one for buttons, one for side zones?

**Comment by yanus171** [comment]
I have released an app version with single setting for all tap zones. Try it - maybe it would be enough. Check changed size with Tap zone preview pref

**Comment by yanus171** [comment]
So we can close an issue?

**Comment by ThomasLeigh** [comment]
Yes, thank You.
