### ISSUE TITLE
Import/Export Favorites

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Flym#48]
Until we don't have a full backup/recovery feature it would be a good idea to enable users to import/export Favorites (now there is only "a workaround" in a form of sharing Favorites, but there is no option to restore them).

Besides then it would be easier to clear app's cache, whenever a user could need it - because it wouldn't be such a loss in that case (if You have many Favorite articles).

**Comment by yanus171** [comment]
ONLY for those who have an ability to restore previously backuped app data (root required): please try the last release (0.7.38) to test favorities restoration
1. In feed setup (pencil) context menu chosse export to OPML
2. Delete app data in system settings
3. In feed setup (pencil) context menu chosse import from OPML
4. Test if starred articles and feed settings are restored correctly

**Comment by ThomasLeigh** [comment]
I'm not sure if I get it correctly. I don't have root. Can I export/import Favorites in that case?

**Comment by yanus171** [comment]
You need root to restore all data in case of problems with new app version

**Comment by ThomasLeigh** [comment]
What should I do to be safe then? Wait for the safe app release?

**Comment by yanus171** [comment]
At least wait for someone else would test it

**Comment by yanus171** [comment]
And there is one more questing to discuss on this issue. Every time user 
edit any feed, the app updates file Flym_auto_backup.opml in root of 
storage directory. When the app starts for the first time (or after data 
clean) the feeds are restored from it.

 This file is generated by the same algorithm as Export to OPML. Since I 
extended the OPML file to include favorites its size was enlarged multiple 
times (~1.5MB).  And to be consistent the app should now update this file 
more often: when user un/stars any article. But this can decrease app 
performance.

And if ee decided to include not only the favorities but, all other 
articles (to preserve un/read state) the update of this file should be even 
more often, which will decrease performance even more..

**Comment by ThomasLeigh** [comment]
Could You change it from automatically created backup to periodically created (choosing interval in app settings)?

**Comment by yanus171** [comment]
Well, I think I can. And in that case we should include all articles in 
opml, not only favorities?

**Comment by ThomasLeigh** [comment]
Yes, definitely - it would be totally great if a user could restore the unread articles also.

**I'm very happy that _Handy NR_ begins to have its own backup ability.** I encourage You to read the rest of backup-related ideas **which could make it even better** and more appealing to users: https://handynewsreader.blogspot.com/2018/11/full-backuprestore.html .

**Comment by yanus171** [comment]
Such backup ideas are subject for another issue

**Comment by yanus171** [comment]
Try app version https://github.com/yanus171/Flym/releases/tag/v0.7.39

**Comment by ThomasLeigh** [comment]
Although I've set backup interval for one minute - it seems not to create it.

**Comment by yanus171** [comment]
The auto backup file is now /storage /feedex/HandyNewsReader_auto_backup.opml

**Comment by ThomasLeigh** [comment]
I know, but this file had older date in its properties, indicating that the file hasn't been updated.

**Comment by ThomasLeigh** [comment]
I know, but this file had older date in its properties, indicating that the file hasn't been updated.

**Comment by yanus171** [comment]
Android has many limits on periodic task for battery save.

**Comment by ThomasLeigh** [comment]
Could You add an additional option to create a backup on demand? (an option to tap in settings to initiate a backup whenever this option be clicked).

**Comment by yanus171** [comment]
What about menu item in article list screen? But we need to test auto 
backup schedule anyway

**Comment by ThomasLeigh** [comment]
_"What about menu item in article list screen?"_

Sounds great! :)


_"But we need to test auto backup schedule anyway"_

Of course. Unfortunately I don't know how to do that because the file indicates that nothing changed - it has modification date March 03, 19:25 - I tried backup interval set to 1 min or 12 hours - so far to no avail.

**Comment by yanus171** [comment]
I have fixed some bugs. try it again https://github.com/yanus171/Flym/releases/tag/v0.7.41

**Comment by ThomasLeigh** [comment]
Thank You, I've tested it and it works great this time. I'll check does the interval for backup still not work in My case.

**Comment by ThomasLeigh** [comment]
So far it works as follows:

1. Most of the time it makes an automatic backup, but not always strictly every 6 hours - instead, if this time span is reached, the app will do the backup *during the earliest (app) launch*. The exact same way I observe in other apps. Maybe it has something to do with Android snooze feature, but I don't know how to workaround it. 

2. Sometimes it stopped working, regardless of excluding the app from battery optimization. I see the newest backup created at 1am today and no further backups, even if I launch the app. So something is still wrong with auto-backup feature.

**Comment by yanus171** [comment]
What is the maximum delay? And what is your interval? The auto backup is not strict. Android determines the best battery optimize time to trigger it

**Comment by yanus171** [comment]
And auto backup is abadoned if battery is low

**Comment by yanus171** [comment]
Try this version. https://github.com/yanus171/Flym/releases/tag/v0.7.45 It should auto backup more stable

**Comment by yanus171** [comment]
Next fix https://github.com/yanus171/Flym/releases/edit/v0.7.46.

**Comment by ThomasLeigh** [comment]
Thank You for all the updates, it seems it works fine now, because whenever I check on the file - its modification date indicates that indeed it has been updated during My 6-hour interval.

Since _Favorites_ are now included in the backup - could we close this issue?

BTW, I've tested the restore feature - **it works great**, it's amazing that now even app's settings can be restored, **so much time-saving**, thank You :) !

**Comment by yanus171** [comment]
I have already lost you, Thomas. I didn't thing this testing would take so 
long. Anyway I am glad that you are back :) Yes you can close the issue. 
There are problems abhor import opml files from other apps, but it is a 
subject of another issue.
С уважением, Алексей

Thomas Leigh <notifications@github.com> 25 марта 2019 г. 16:13:08 написал:

**Comment by ThomasLeigh** [comment]
I'm really sorry for such a long time for My response, sometimes I have difficulties with that. But as always I want to do My best.

**Comment by ThomasLeigh** [comment]
I've updated the backup/restore section on the website: https://handynewsreader.blogspot.com/2018/11/full-backuprestore.html .

**Comment by yanus171** [comment]
May be its worth to paste that text in this thread
