### ISSUE TITLE
"Mark icon on items image in the article list" confusing me

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Flym#50]
This new feature is confusing me. I don't no how to use/interpret it. To me all unread articles are new. Please describe me the sense. Thank you

**Comment by yanus171** [comment]
And what's now? Is it still confusing you?

**Comment by SIRSteiner** [comment]
Thank you! I understand it. But in the meanwhile I found that I (for myself) don't need this feature. This means that maybe other users will find it very useful.

**Comment by yanus171** [comment]
We have now setting to turn it off. So I close an issue
