### ISSUE TITLE
Feature request: unread count near folder name

### ISSUE THREAD

**Issue by seth100** [yanus171/Flym#58]
Hi,

I would like to have the total count of unread feeds right on the right of the folder name in the feed list from the left menu.
Would it be possibile? I really need that to definitely remove other RSS readers and switch to this.

Thanks

**Comment by yanus171** [comment]
OK I will try

**Comment by yanus171** [comment]
Try this release https://github.com/yanus171/Flym/releases/tag/0.7.35

**Comment by seth100** [comment]
@yanus171 That's great thank you it works as expected, good job!
