### ISSUE TITLE
Feature request list

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Flym#59]
-Add the number of unread news next to the folders

-Fix the suggest link (open the mail app but doesn't set the address mail)

-Add black theme (The backgroung is black | The words are white)

-Add edit folder options that look like edit feed options

-Add micro-original text on article list
(Ex.
TITLE
Original text of 10 words)

**Comment by yanus171** [comment]
Please make each point ss a separate issue
С уважением, Алексей

RAMAR-RAR <notifications@github.com> 7 февраля 2019 г. 19:47:46 написал:
