### ISSUE TITLE
Error at line 123, column 12,....

### ISSUE THREAD

**Issue by shadowbone94** [yanus171/Flym#67]
Not certain if its a bug or not but everytime I try adding a new custome feed it shoes an error like this.

Any suggestions?

**Comment by yanus171** [comment]
This is an error of parsing a feed. What url and load type you use?

**Comment by shadowbone94** [comment]
@yanus171 I simply go about adding a custome feed, type in BBC news for instsnce and then choose the first feed which being BBC News Home.

But then no articles load and then when I pull the side drawer I see these error just below the feed tab.

**Comment by yanus171** [comment]
This site has no rss channel. But you can load it as web page. Do the following :
- add to settings, additionals, Content extract rules text: story-body__inner
- in feed settings set url to https://www.bbc.com/news, and in Load type set Web 
- in feed settings go to filter tab and add Accept rule news\/.+?-\d+ as a regular expression, applied to title.

**Comment by shadowbone94** [comment]
@yanus171 thanks, that helped. 

Just out of curiosity,  does any other feeds(other than google news feeds) work within the search tool that can be viewed as an rss feed and not webview?

**Comment by yanus171** [comment]
The BBC site has no rss feed. Try any rss link or url of site which has 
rss. It should work with RSS load type out of the box.

**Comment by shadowbone94** [comment]
@yanus171 Sorry but could you please provide me with an example feed url because no matter which site I try I end up with that error.

**Comment by yanus171** [comment]
Yes you are right. Add feed seach had malfunction. Try latest release

**Comment by shadowbone94** [comment]
@yanus171 Brilliant!  Absolutely brilliant.  The last build rectifies this issue and I can now add feeds directly from the searched list.
Thanks for that. :+1:
