### ISSUE TITLE
Build error: cannot find symbol R.drawable.cup_empty

### ISSUE THREAD

**Issue by relan** [yanus171/Flym#72]
0.7.36 fails to build due to missing drawables: https://f-droid.org/wiki/page/ru.yanus171.feedexfork/lastbuild_134.

**Comment by yanus171** [comment]
It seems that I forgot to add new files before commit. Will fix it in the evening

**Comment by yanus171** [comment]
I have pushed the commit with absent files. The build should be ok now

**Comment by relan** [comment]
Updated in https://gitlab.com/fdroid/fdroiddata/commit/866c4678177c557cc6fa14181f7b4f169f3416b2, thanks!
