### ISSUE TITLE
A Tumblr feed doesn't work.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Flym#87]
When I add this feed, it doesn't show any item (article) - although when loaded on the desktop web browser, it shows a couple of them. This is the address:

http://abyjezykgietki.tumblr.com/rss

**Comment by ThomasLeigh** [comment]
After upgrading to the newest ver. of _Handy_ there is an error message, I suppose it is connected with this feed mentioned above, but I'm not sure. **This message is visible on every _Handy_ screen**, regardless of progress technical info disabled in settings.

This is how it looks:
https://drive.google.com/file/d/1kQdRfrIKruFqlV713jEWUL8phMRah556/view?usp=sharing

**Comment by yanus171** [comment]
Try it https://github.com/yanus171/Flym/releases/tag/v0.7.43
