### ISSUE TITLE
An application crashes / error when accessing the "Create Auto Backup" feature

### ISSUE THREAD

**Issue by ahyar92** [yanus171/Flym#92]
Hi @yanus171 , I found a BUG, please see the details below:

### Expected behavior
Supposedly, I can access the "Create Auto Backup" feature without errors

### Actual behavior
When I tried to click on the "Create Auto Backup" feature, the application crashed.

### How  to reproduce
1. Instal and Open
2. Click on the "Create Auto Backup" feature

### Environment
Tested on  1 devices:

<table>
<thead>
<tr><th>Device</th><th>Android Version</th>
</thead>
<tbody>
<tr><td>VIVO Y81</td><td>Oreo 8.1.0 (CPU: Octa-core Max 2.0 GHz, RAM: 3 GB)</td>
</table>

### Recording Of The Bug
You can see the recording below:
https://youtu.be/RhMNCr5j5Jk

### Logcat
``` 03-13 13:23:38.671  2317  2533 E AndroidRuntime: FATAL EXCEPTION: IntentService[FetcherService]
03-13 13:23:38.671  2317  2533 E AndroidRuntime: Process: ru.yanus171.feedexfork, PID: 2317
03-13 13:23:38.671  2317  2533 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void ru.yanus171.feedexfork.view.StatusText$FetcherObservable.ClearError()' on a null object reference
03-13 13:23:38.671  2317  2533 E AndroidRuntime: 	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:210)
03-13 13:23:38.671  2317  2533 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
03-13 13:23:38.671  2317  2533 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-13 13:23:38.671  2317  2533 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:192)
03-13 13:23:38.671  2317  2533 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65) ```

**Comment by yanus171** [comment]
Try the latest app release 
https://github.com/yanus171/Flym/releases/tag/v0.7.43

**Comment by ahyar92** [comment]
Can you confirm if it's a BUG? @yanus171

**Comment by yanus171** [comment]
Yes it is a bug, that was fixed several app versions ago

**Comment by ahyar92** [comment]
It's safe in version v0.7.43

**Comment by yanus171** [comment]
What do you mean by safe? If you can confirm bug fix, close the issue
